services:
  app:
    build: .
    container_name: kicksync-backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1536M
        reservations:
          cpus: '0.5'
          memory: 1024M
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+UseZGC -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -javaagent:/app/scouter/agent.java/scouter.agent.jar -Dscouter.config=/app/scouter/agent.java/conf/scouter.conf -Dobj_name=kicksync-prod-01 -Dscouter.host.name=kicksync-host --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.management/java.lang.management=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DATABASE_URL=${DB_URL}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - IAMPORT_KEY=${IAMPORT_KEY}
      - IAMPORT_SECRET_KEY=${IAMPORT_SECRET}
      - TOSS_KEY=${TOSS_KEY}
    volumes:
      - /Users/gminnimk/Downloads/util/scouter/scouter:/app/scouter
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - kicksync-net

  db:
    image: mysql:8.0
    container_name: kicksync-db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
    command:
      - --innodb-buffer-pool-size=1024M
    environment:
      MYSQL_DATABASE: kicksync
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kicksync-net

  redis:
    image: redis:alpine
    container_name: kicksync-redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
    networks:
      - kicksync-net

  nginx:
    image: nginx:alpine
    container_name: kicksync-nginx
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - kicksync-net

volumes:
  db_data:

networks:
  kicksync-net:
    driver: bridge
